/**
 * 内置主流服务商预设（§3.1 表格的代码化，含余额端点信息）。
 * 这 13 家保留原 slug；cc-switch 同名条目以 -cc/-codex 后缀区分（见 cc-switch.ts）。
 */
import type { ProviderPreset } from './types';

type LegacyPreset = Omit<ProviderPreset, 'presetKey' | 'defaultProtocol' | 'endpoints' | 'legacySlugs'>;

const legacyProviders: LegacyPreset[] = [
  {
    slug: 'openai',
    name: 'OpenAI',
    protocol: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    category: 'official',
    logo: '/logos/openai.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '用量 API，需按当前官方文档适配' },
    websiteUrl: 'https://openai.com',
    consoleUrl: 'https://platform.openai.com/api-keys',
  },
  {
    slug: 'anthropic',
    name: 'Anthropic',
    protocol: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    category: 'official',
    logo: '/logos/anthropic.svg',
    modelsEndpoint: 'GET /v1/models',
    balance: { supported: false, note: '无公开余额接口，请前往 Console 查看' },
    websiteUrl: 'https://www.anthropic.com',
    consoleUrl: 'https://console.anthropic.com',
  },
  {
    slug: 'gemini',
    name: 'Google Gemini',
    protocol: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    category: 'official',
    logo: '/logos/gemini.svg',
    modelsEndpoint: 'GET /v1beta/models',
    balance: { supported: false },
    websiteUrl: 'https://ai.google.dev',
    consoleUrl: 'https://aistudio.google.com/apikey',
  },
  {
    slug: 'deepseek',
    name: 'DeepSeek',
    protocol: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    category: 'cn_official',
    logo: '/logos/deepseek.svg',
    modelsEndpoint: 'GET /models',
    balance: { endpoint: '//user/balance', method: 'GET', supported: true, note: 'origin 级端点（不在 /v1 下）；返回 CNY/USD 双币种' },
    websiteUrl: 'https://www.deepseek.com',
    consoleUrl: 'https://platform.deepseek.com',
  },
  {
    slug: 'kimi',
    name: 'Moonshot Kimi',
    protocol: 'openai',
    baseUrl: 'https://api.moonshot.cn/v1',
    category: 'cn_official',
    logo: '/logos/kimi.svg',
    modelsEndpoint: 'GET /models',
    balance: { endpoint: '/users/me/balance', method: 'GET', supported: true },
    websiteUrl: 'https://www.moonshot.cn',
    consoleUrl: 'https://platform.moonshot.cn',
  },
  {
    slug: 'zhipu',
    name: '智谱 GLM',
    protocol: 'openai',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    category: 'cn_official',
    logo: '/logos/zhipu.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '无简易接口，控制台查看' },
    websiteUrl: 'https://open.bigmodel.cn',
    consoleUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
  },
  {
    slug: 'qwen',
    name: '阿里百炼（通义 Qwen）',
    protocol: 'openai',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    category: 'cn_official',
    logo: '/logos/qwen.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '控制台查看' },
    websiteUrl: 'https://bailian.console.aliyun.com',
    consoleUrl: 'https://bailian.console.aliyun.com/#/api-key',
  },
  {
    slug: 'volcengine',
    name: '火山方舟（豆包）',
    protocol: 'openai',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    category: 'cn_official',
    logo: '/logos/huoshan.png',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '控制台查看' },
    websiteUrl: 'https://www.volcengine.com/product/ark',
    consoleUrl: 'https://console.volcengine.com/ark',
  },
  {
    slug: 'xai',
    name: 'xAI Grok',
    protocol: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    category: 'official',
    logo: '/logos/xai.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '需确认' },
    websiteUrl: 'https://x.ai',
    consoleUrl: 'https://console.x.ai',
  },
  {
    slug: 'mistral',
    name: 'Mistral',
    protocol: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    category: 'official',
    logo: '/logos/mistral.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '控制台查看' },
    websiteUrl: 'https://mistral.ai',
    consoleUrl: 'https://console.mistral.ai',
  },
  {
    slug: 'openrouter',
    name: 'OpenRouter',
    protocol: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    category: 'aggregator',
    logo: '/logos/openrouter.svg',
    modelsEndpoint: 'GET /models',
    balance: { endpoint: '/auth/key', method: 'GET', supported: true, note: '返回用量/限额' },
    websiteUrl: 'https://openrouter.ai',
    consoleUrl: 'https://openrouter.ai/keys',
  },
  {
    slug: 'siliconflow',
    name: 'SiliconFlow',
    protocol: 'openai',
    baseUrl: 'https://api.siliconflow.cn/v1',
    category: 'aggregator',
    logo: '/logos/siliconflow.svg',
    modelsEndpoint: 'GET /models',
    balance: { endpoint: '/user/info', method: 'GET', supported: true },
    websiteUrl: 'https://siliconflow.cn',
    consoleUrl: 'https://cloud.siliconflow.cn',
  },
  {
    slug: 'ppio',
    name: 'PPIO',
    protocol: 'openai',
    baseUrl: 'https://api.ppinfra.com/v3/openai',
    category: 'aggregator',
    logo: '/logos/ppio.svg',
    modelsEndpoint: 'GET /models',
    balance: { supported: false, note: '需确认' },
    websiteUrl: 'https://ppinfra.com',
    consoleUrl: 'https://ppinfra.com/user/key',
  },
];

export const LEGACY_PRESETS: ProviderPreset[] = legacyProviders.map((preset) => ({
  ...preset,
  presetKey: preset.slug,
  defaultProtocol: preset.protocol,
  endpoints: [
    {
      protocol: preset.protocol,
      baseUrl: preset.baseUrl,
      selectedVariantSlug: preset.slug,
      sourceApps: [],
      knownModels: [],
      modelCatalogComplete: false,
      alternateCandidates: [
        {
          variantSlug: preset.slug,
          baseUrl: preset.baseUrl,
          sourceApps: [],
          supported: preset.supported ?? true,
          authMode: preset.authMode ?? 'api-key',
        },
      ],
    },
  ],
  legacySlugs: [preset.slug],
}));
